### ISSUE TITLE
Please get rid of your gitconfig in this repo!

### ISSUE THREAD

**Issue by benbieler** [Ma27/dotfiles#1]
https://github.com/Ma27/dotfiles/blob/master/git/gitconfig

**Comment by benbieler** [comment]
I don't understand why anybody would want a different `$HOME/.gitconfig` than their own.

**Comment by Ma27** [comment]
why though? There's no secret revealed.

> I don't understand why anybody would want a different $HOME/.gitconfig than their own.
Well, I use this as a "backup" for my shell environment and it's highly opinionated (sth. like [this](https://github.com/Ma27/dotfiles/blob/master/scripts/alias.sh#L32-L39) for instance).
If you'd like to use this, I'd recommend to create a fork and customize everything for your needs :)

**Comment by benbieler** [comment]
Well I am not the git user "Maximilian Bosch", and my git signing key is not "A376CC9C". So after running `bin/install` MY .gitconfig is replaced by yours. As a result I would have to manually change the file again.

> If you'd like to use this, I'd recommend to create a fork and customize everything for your needs :)

Ok. Well - then I missed the point of the repo if that is the case. Sorry for creating any hassle.

**Comment by Ma27** [comment]
> MY .gitconfig is replaced by yours

oh shit, I'm sorry. But basically you're right, I should make this way more clear in the README...
